export const products = [
  {
    id: 1,
    user: "Shivani (CSE)",
    title: "Raspberry Pi 4 Model B",
    price: "₹8,000",
    numericPrice: 8000, // Helper for sorting
    tag: "Electronics",
    category: "electronics",
    branch: "cs",
    year: 4,
    condition: "Like New",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "2m ago",
    views: 145,
    saves: 32,
    location: "Near ATC",
    image: "https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#FF5733", // Orange
    description: "4GB RAM model, barely used, includes power adapter and case. Purchased for a semester project that is now complete.",
    highlights: ["4 GB RAM", "WiFi + BT 5.0", "Case Included", "GPIO Tested"],
    specs: [{label:"Model",value:"Pi 4B"},{label:"RAM",value:"4GB"},{label:"Storage",value:"32GB SD"},{label:"USB",value:"3.0 x2"}],
    sellerRating: 4.8,
  },
  {
    id: 2,
    user: "Amit (Mech)",
    title: "Engineering Drafter (Omega)",
    price: "₹450",
    numericPrice: 450,
    tag: "Engineering",
    category: "stationery",
    branch: "mech",
    year: 3,
    condition: "Good",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "5m ago",
    views: 28,
    saves: 5,
    location: "Hostel 2",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80"
    ],
    accent: "#00D9FF", // Cyan
    description: "Standard Omega drafter used for ED-1 and ED-2. Mechanics are smooth, scale is clean.",
    highlights: ["Omega Brand", "Smooth Pivot", "Clean Scale", "Bag Included"],
    specs: [{label:"Brand",value:"Omega"},{label:"Material",value:"Steel/Plastic"},{label:"Type",value:"Mini Drafter"}],
    sellerRating: 4.5,
  },
  {
    id: 3,
    user: "Rahul (IT)",
    title: "Casio FX-991EX Classwiz",
    price: "₹1,200",
    numericPrice: 1200,
    tag: "Tools",
    category: "stationery",
    branch: "cs",
    year: 2,
    condition: "New",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "12m ago",
    views: 67,
    saves: 18,
    location: "Library",
    image: "https://images.unsplash.com/photo-1611348524140-53c9a25263d6?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1611348524140-53c9a25263d6?auto=format&fit=crop&w=800&q=80"
    ],
    accent: "#F59E0B", // Amber
    description: "Original Casio FX-991EX. Allowed in exams. Solar powered and battery backup.",
    highlights: ["Solar", "552 Functions", "High Res LCD", "Exam Legal"],
    specs: [{label:"Model",value:"FX-991EX"},{label:"Power",value:"Solar/Bat"},{label:"Display",value:"Dot Matrix"}],
    sellerRating: 5.0,
  },
  {
    id: 5,
    user: "Neha (ECE)",
    title: "Arduino Mega Kit",
    price: "₹2,500",
    numericPrice: 2500,
    tag: "Electronics",
    category: "electronics",
    branch: "ece",
    year: 4,
    condition: "Like New",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "25m ago",
    views: 102,
    saves: 34,
    location: "Lab Block",
    image: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&w=800&q=80",
    images: [
       "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&w=800&q=80"
    ],
    accent: "#10B981", // Emerald
    description: "Full Arduino Mega 2560 kit with jumper wires, breadboard, and sensors.",
    highlights: ["Mega 2560", "USB Cable", "Sensors", "Jumper Wires"],
    specs: [{label:"Board",value:"Mega 2560"},{label:"IO Pins",value:"54"},{label:"Input",value:"7-12V"}],
    sellerRating: 4.9,
  },

     {
    id: 6,
    user: "Karan (CSE)",
    title: "Mechanical Keyboard (Red Switches)",
    price: "₹3,200",
    numericPrice: 3200,
    tag: "Accessories",
    category: "electronics",
    branch: "cs",
    year: 3,
    condition: "Like New",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "30m ago",
    views: 89,
    saves: 21,
    location: "Hostel 5",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#6366F1",
    description: "RGB mechanical keyboard with red switches, great for coding and gaming. Barely used in one semester.",
    highlights: ["RGB Backlight", "Red Switches", "Full Size", "Detachable Cable"],
    specs: [
      { label: "Type", value: "Mechanical" },
      { label: "Switch", value: "Red" },
      { label: "Layout", value: "104 Keys" }
    ],
    sellerRating: 4.7,
  },
  {
    id: 7,
    user: "Meera (EEE)",
    title: "Digital Multimeter (UNI-T)",
    price: "₹750",
    numericPrice: 750,
    tag: "Lab Tools",
    category: "electronics",
    branch: "eee",
    year: 2,
    condition: "Good",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "45m ago",
    views: 54,
    saves: 9,
    location: "Lab Block",
    image: "https://images.unsplash.com/photo-1581093458791-9d42e3c533af?auto=format&fit=crop&w=1000&q=80",
    images: [
      "https://images.unsplash.com/photo-1581093458791-9d42e3c533af?auto=format&fit=crop&w=1000&q=80"
    ],
    accent: "#EF4444",
    description: "Digital multimeter used for basic electronics and machines lab. All ranges working fine with new battery.",
    highlights: ["AC/DC Voltage", "Continuity Buzzer", "Auto Range", "Backlight"],
    specs: [
      { label: "Type", value: "Digital" },
      { label: "Brand", value: "UNI-T" },
      { label: "Battery", value: "9V" }
    ],
    sellerRating: 4.6,
  },
  {
    id: 8,
    user: "Saurabh (Civil)",
    title: "Engineering Drawing Board + T-Square",
    price: "₹1,000",
    numericPrice: 1000,
    tag: "Engineering",
    category: "stationery",
    branch: "civil",
    year: 1,
    condition: "Good",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "1h ago",
    views: 40,
    saves: 7,
    location: "Hostel 3",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#0EA5E9",
    description: "Full-size drawing board with wooden T-square, perfect for ED labs and first-year engineering graphics.",
    highlights: ["Full Size", "Wooden Board", "Included T-Square", "Smooth Surface"],
    specs: [
      { label: "Board Size", value: "A1" },
      { label: "Material", value: "Wood" }
    ],
    sellerRating: 4.3,
  },
  {
    id: 9,
    user: "Priya (CSE)",
    title: "Noise Cancelling Headphones",
    price: "₹2,800",
    numericPrice: 2800,
    tag: "Accessories",
    category: "electronics",
    branch: "cs",
    year: 3,
    condition: "Like New",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "1h ago",
    views: 120,
    saves: 37,
    location: "Library Lawn",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#22C55E",
    description: "Over-ear Bluetooth headphones with passive noise isolation. Great for late-night coding in hostels.",
    highlights: ["Over Ear", "Bluetooth", "Long Battery", "Foldable"],
    specs: [
      { label: "Type", value: "Wireless" },
      { label: "Battery Life", value: "20+ hrs" }
    ],
    sellerRating: 4.8,
  },
  {
    id: 10,
    user: "Ankit (IT)",
    title: "Laptop Cooling Pad (5 Fan)",
    price: "₹900",
    numericPrice: 900,
    tag: "Accessories",
    category: "electronics",
    branch: "it",
    year: 3,
    condition: "Good",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "2h ago",
    views: 33,
    saves: 6,
    location: "Canteen",
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#FB7185",
    description: "5-fan cooling pad with adjustable height, useful during long online labs and gaming sessions.",
    highlights: ["5 Fans", "Blue LED", "Height Adjustable", "USB Powered"],
    specs: [
      { label: "Fans", value: "5" },
      { label: "Ports", value: "2x USB" }
    ],
    sellerRating: 4.2,
  },
  {
    id: 11,
    user: "Ishita (ECE)",
    title: "Soldering Station + Toolkit",
    price: "₹1,400",
    numericPrice: 1400,
    tag: "Lab Tools",
    category: "electronics",
    branch: "ece",
    year: 3,
    condition: "Good",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "2h ago",
    views: 76,
    saves: 19,
    location: "ECE Lab",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#F97316",
    description: "Temperature-controlled soldering iron with stand, solder wire, flux, and basic toolkit for DIY projects.",
    highlights: ["Temp Control", "Stand Included", "Toolkit", "For PCBs"],
    specs: [
      { label: "Power", value: "60W" },
      { label: "Temp Range", value: "200–450°C" }
    ],
    sellerRating: 4.6,
  },
  {
    id: 12,
    user: "Rohit (Mech)",
    title: "Scientific Calculator (FX-991MS)",
    price: "₹650",
    numericPrice: 650,
    tag: "Tools",
    category: "stationery",
    branch: "mech",
    year: 2,
    condition: "Good",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "3h ago",
    views: 48,
    saves: 11,
    location: "Workshop Block",
    image: "https://images.unsplash.com/photo-1611348524140-53c9a25263d6?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1611348524140-53c9a25263d6?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#14B8A6",
    description: "Casio FX-991MS, fully working, used for first and second year maths & mechanics.",
    highlights: ["Casio Original", "Long Battery", "Exam Friendly"],
    specs: [
      { label: "Model", value: "FX-991MS" },
      { label: "Power", value: "Battery" }
    ],
    sellerRating: 4.4,
  },
  {
    id: 13,
    user: "Nisha (CSE)",
    title: "External Hard Drive 1TB",
    price: "₹3,000",
    numericPrice: 3000,
    tag: "Storage",
    category: "electronics",
    branch: "cs",
    year: 4,
    condition: "Like New",
    type: "sale",
    isTrending: true,
    isVerified: true,
    timeAgo: "3h ago",
    views: 110,
    saves: 29,
    location: "Near Library",
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#A855F7",
    description: "1TB external HDD for project backups, movies, and lab files. USB 3.0, works on Windows and Linux.",
    highlights: ["1TB", "USB 3.0", "Portable", "Plug & Play"],
    specs: [
      { label: "Capacity", value: "1TB" },
      { label: "Interface", value: "USB 3.0" }
    ],
    sellerRating: 4.9,
  },
  {
    id: 14,
    user: "Aditya (Civil)",
    title: "Surveying Lab Kit (Mini)",
    price: "₹1,800",
    numericPrice: 1800,
    tag: "Lab Tools",
    category: "tools",
    branch: "civil",
    year: 3,
    condition: "Good",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "4h ago",
    views: 29,
    saves: 8,
    location: "Civil Dept",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#22C55E",
    description: "Mini surveying kit with measuring tape, ranging rods (foldable), and basic accessories for lab work.",
    highlights: ["Measuring Tape", "Foldable Rods", "Carrying Bag"],
    specs: [
      { label: "Tape Length", value: "30m" },
      { label: "Usage", value: "Survey Lab" }
    ],
    sellerRating: 4.1,
  },
  {
    id: 15,
    user: "Tanya (CSE)",
    title: "Laptop Stand (Aluminium)",
    price: "₹700",
    numericPrice: 700,
    tag: "Accessories",
    category: "stationery",
    branch: "cs",
    year: 2,
    condition: "Like New",
    type: "sale",
    isTrending: false,
    isVerified: true,
    timeAgo: "4h ago",
    views: 61,
    saves: 14,
    location: "Girls Hostel",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80"
    ],
    accent: "#3B82F6",
    description: "Ergonomic aluminium laptop stand, helps with posture during long coding and assignment sessions.",
    highlights: ["Ergonomic", "Foldable", "Metal Build", "Stable"],
    specs: [
      { label: "Material", value: "Aluminium" },
      { label: "Height", value: "Adjustable" }
    ],
    sellerRating: 4.5,
  },

]